run:
  go: 1.22
  concurrency: 4
  timeout: 10m

linters:
  disable-all: true
  enable:
    - asciicheck
    - gofmt
    - goimports
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - typecheck
    - unconvert
    - whitespace
