name: release

on:
  push:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.5'

      - name: Build Admin dashboard UI
        run: npm --prefix=./ui ci && npm --prefix=./ui run build

      # Temporary disable as the types can have random generated identifiers making it non-deterministic.
      #
      # # Similar to the above, the jsvm types are pregenerated locally
      # # but its here to ensure that it wasn't forgotten to be executed.
      # - name: Generate jsvm types
      #   run: go run ./plugins/jsvm/internal/types/types.go

      - name: Run linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61

      - name: Run tests
        run: go test ./...

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
